In [1]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt

In [2]:
ratings = pd.read_csv("ml-latest-small/ratings.csv")
movies = pd.read_csv("ml-latest-small/movies.csv")

In [3]:
movies.head()

movieId                               title  \
0        1                    Toy Story (1995)   
1        2                      Jumanji (1995)   
2        3             Grumpier Old Men (1995)   
3        4            Waiting to Exhale (1995)   
4        5  Father of the Bride Part II (1995)   

                                        genres  
0  Adventure|Animation|Children|Comedy|Fantasy  
1                   Adventure|Children|Fantasy  
2                               Comedy|Romance  
3                         Comedy|Drama|Romance  
4                                       Comedy

In [4]:
ratings = ratings.drop(["timestamp"],axis=1)
ratings.head()

userId  movieId  rating
0       1        1     4.0
1       1        3     4.0
2       1        6     4.0
3       1       47     5.0
4       1       50     5.0

In [5]:
ratings = ratings.pivot_table(index=["userId"], columns=["movieId"], values="rating")
ratings.head()

movieId  1       2       3       4       5       6       7       8       \
userId                                                                    
1           4.0     NaN     4.0     NaN     NaN     4.0     NaN     NaN   
2           NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
3           NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
4           NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
5           4.0     NaN     NaN     NaN     NaN     NaN     NaN     NaN   

movieId  9       10       ...    193565  193567  193571  193573  193579  \
userId                    ...                                             
1           NaN     NaN   ...       NaN     NaN     NaN     NaN     NaN   
2           NaN     NaN   ...       NaN     NaN     NaN     NaN     NaN   
3           NaN     NaN   ...       NaN     NaN     NaN     NaN     NaN   
4           NaN     NaN   ...       NaN     NaN     NaN     NaN     NaN   
5           NaN     NaN   ...       NaN     NaN     NaN     NaN     NaN   

movieId  193581  193583  193585  193587  193609  
userId                                           
1           NaN     NaN     NaN     NaN     NaN  
2           NaN     NaN     NaN     NaN     NaN  
3           NaN     NaN     NaN     NaN     NaN  
4           NaN     NaN     NaN     NaN     NaN  
5           NaN     NaN     NaN     NaN     NaN  

[5 rows x 9724 columns]

In [6]:
cols = ratings.columns
cols

Int64Index([     1,      2,      3,      4,      5,      6,      7,      8,
                 9,     10,
            ...
            193565, 193567, 193571, 193573, 193579, 193581, 193583, 193585,
            193587, 193609],
           dtype='int64', name='movieId', length=9724)

In [22]:
ratebool = ratings>0
# ratebool.iloc[].sum()
# ratings.index

In [8]:
ratedef = ratings.fillna(0)
ratedef = ratedef.div(5)
ratedef.head()

movieId  1       2       3       4       5       6       7       8       \
userId                                                                    
1           0.8     0.0     0.8     0.0     0.0     0.8     0.0     0.0   
2           0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
3           0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
4           0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
5           0.8     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

movieId  9       10       ...    193565  193567  193571  193573  193579  \
userId                    ...                                             
1           0.0     0.0   ...       0.0     0.0     0.0     0.0     0.0   
2           0.0     0.0   ...       0.0     0.0     0.0     0.0     0.0   
3           0.0     0.0   ...       0.0     0.0     0.0     0.0     0.0   
4           0.0     0.0   ...       0.0     0.0     0.0     0.0     0.0   
5           0.0     0.0   ...       0.0     0.0     0.0     0.0     0.0   

movieId  193581  193583  193585  193587  193609  
userId                                           
1           0.0     0.0     0.0     0.0     0.0  
2           0.0     0.0     0.0     0.0     0.0  
3           0.0     0.0     0.0     0.0     0.0  
4           0.0     0.0     0.0     0.0     0.0  
5           0.0     0.0     0.0     0.0     0.0  

[5 rows x 9724 columns]

In [9]:
p = []
p.append([2,3])
p.append([3,10])
p = np.array(p)
q = np.array([3,4])
p
for i in p:
    print(i)

[2 3]
[ 3 10]


In [10]:
current = np.array(ratedef.iloc[2])
user = current
userlen = np.sum(user>0)
intersect = np.sum(current * user > 0)
temp = intersect / (np.sum(current>0) + userlen - intersect)
# ((ratedef>0)*ratedef).head()

In [11]:
def sigmoid(value):
    return 1/(1 + np.exp(-value))

In [12]:
def proximity(ratings, user):
#     prox = np.array(ratings.shape)
    prox = []
    for index, row in ratings.iterrows():
        current = np.array(row)
#         temp = 1 - sigmoid(np.absolute(current - user))
        temp = 1 - sigmoid(current - user)
        prox.append(temp)
    prox = np.array(prox)
    print(prox[2])
    return prox

In [13]:
def significance(ratings, rmedian, user):
    sign = []
    for index, row in ratings.iterrows():
        current = np.array(row)
#         temp = sigmoid(np.absolute(current - rmedian)*np.absolute(user - rmedian))
        temp = sigmoid((current - rmedian)*(user - rmedian))
        sign.append(temp)
    sign = np.array(sign)
    print(sign[2])
    return sign

In [14]:
def singularity(ratings, mmeans, user):
    sin = []
    for index, row in ratings.iterrows():
        current = np.array(row)
#         temp = 1 - sigmoid(np.absolute((current+user)/2 - mmeans))
        temp = 1 - sigmoid((current+user)/2 - mmeans)
        sin.append(temp)
    sin = np.array(sin)
    print(sin[2])
    return sin

In [15]:
def pss(ratings, user):
    median = np.median(np.array(ratings))
    mmeans = np.array(ratings.mean())
    simpss = proximity(ratings, user) * significance(ratings, median, user) * singularity(ratings, mmeans, user)
    simpss = simpss * (user>0)
#     simpss = np.cross(np.cross(proximity(ratings, user), significance(ratings, median, user)), singularity(ratings, mmeans, user))
#     simpss = []
#     for index, row in ratings.iterrows():
#         current = np.array(row)
        
    simpss = np.sum(simpss, axis=1)
    print(simpss[2])
    return simpss

In [16]:
def jaccard(ratings, user):
    jac = []
    inte = []
    userlen = np.sum(user>0)
    for index, row in ratings.iterrows():
        current = np.array(row)
        intersect = np.sum(current * user > 0)
#         temp = intersect / (np.sum(current>0) + userlen - intersect)
        temp = intersect / (np.sum(current>0) * userlen)
        jac.append(temp)
        inte.append(intersect)
    jac = np.array(jac)
    print(jac[2])
#     print(user)
#     print(rating)
    return jac

In [17]:
def jpss(ratings, user):
    return pss(ratings, user) * jaccard(ratings, user)

In [18]:
def urp(ratings, user):
    urprate = []
    umean = np.mean(user)
    ustd = np.std(user)
    for index, row in ratings.iterrows():
        current = np.array(row)
#         temp = 1 + sigmoid(np.absolute((umean - np.mean(current))*(ustd - np.std(current))))
        temp = 1 - sigmoid((umean - np.mean(current))*(ustd - np.std(current)))
        urprate.append(temp)
    urprate = np.array(urprate)
    print(urprate[2])
    return urprate

In [19]:
def similarity_calculator(ratings, user):
    return jpss(ratings, user) * urp(ratings, user)

In [20]:
type(ratings.index)

pandas.core.indexes.numeric.Int64Index

In [23]:
nk = []
for i in ratedef.index:
    if ratebool.loc[i].sum() > 50:
        nk.append(ratedef.loc[i])
ratedefactive = pd.DataFrame(nk)
ratedefactive.head()

movieId  1       2       3       4       5       6       7       8       \
1           0.8     0.0     0.8     0.0     0.0     0.8     0.0     0.0   
4           0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
6           0.0     0.8     1.0     0.6     1.0     0.8     0.8     0.6   
7           0.9     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
10          0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

movieId  9       10       ...    193565  193567  193571  193573  193579  \
1           0.0     0.0   ...       0.0     0.0     0.0     0.0     0.0   
4           0.0     0.0   ...       0.0     0.0     0.0     0.0     0.0   
6           0.0     0.6   ...       0.0     0.0     0.0     0.0     0.0   
7           0.0     0.0   ...       0.0     0.0     0.0     0.0     0.0   
10          0.0     0.0   ...       0.0     0.0     0.0     0.0     0.0   

movieId  193581  193583  193585  193587  193609  
1           0.0     0.0     0.0     0.0     0.0  
4           0.0     0.0     0.0     0.0     0.0  
6           0.0     0.0     0.0     0.0     0.0  
7           0.0     0.0     0.0     0.0     0.0  
10          0.0     0.0     0.0     0.0     0.0  

[5 rows x 9724 columns]

In [24]:
testuser = np.array(ratedef.iloc[0])
testuser

array([0.8, 0. , 0.8, ..., 0. , 0. , 0. ])

In [25]:
simval = similarity_calculator(ratedefactive, testuser)

[0.68997448 0.31002552 0.450166   ... 0.5        0.5        0.5       ]
[0.5        0.5        0.68997448 ... 0.5        0.5        0.5       ]
[0.48889072 0.44656724 0.3045072  ... 0.50046296 0.50046296 0.5005291 ]
33.26502810709903
0.00045299802328135295
0.500003585231868


In [26]:
simval[:10]

array([0.05473023, 0.01484024, 0.00753455, 0.01234997, 0.00317555,
       0.01816259, 0.01339435, 0.01928836, 0.0256779 , 0.00963344])

In [27]:
topN = sorted([(simval[i],i) for i in range(len(simval))],reverse=True)
topN[:5]

[(0.054730226248996185, 0),
 (0.037821130032614, 308),
 (0.035962867121336756, 24),
 (0.034707351853669535, 61),
 (0.03051942678606174, 114)]

In [28]:
topNindex = [i[1] for i in topN][:5]
topNindex

[0, 308, 24, 61, 114]

In [29]:
movies = []
topNnumpy = []

for index in topNindex:
    movies.extend([i for i in cols if ratings.iloc[index][i] > 3])
    topNnumpy.append(ratings.iloc[index])
topNdf = pd.DataFrame(topNnumpy)
movies = set(movies)

In [30]:
len(movies)

621

In [31]:
topNdf

movieId  1       2       3       4       5       6       7       8       \
1           4.0     NaN     4.0     NaN     NaN     4.0     NaN     NaN   
309         NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
25          NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
62          NaN     4.0     NaN     NaN     NaN     4.5     NaN     NaN   
115         NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   

movieId  9       10       ...    193565  193567  193571  193573  193579  \
1           NaN     NaN   ...       NaN     NaN     NaN     NaN     NaN   
309         NaN     NaN   ...       NaN     NaN     NaN     NaN     NaN   
25          NaN     NaN   ...       NaN     NaN     NaN     NaN     NaN   
62          NaN     NaN   ...       NaN     NaN     NaN     NaN     NaN   
115         NaN     NaN   ...       NaN     NaN     NaN     NaN     NaN   

movieId  193581  193583  193585  193587  193609  
1           NaN     NaN     NaN     NaN     NaN  
309         NaN     NaN     NaN     NaN     NaN  
25          NaN     NaN     NaN     NaN     NaN  
62          NaN     NaN     NaN     NaN     NaN  
115         NaN     NaN     NaN     NaN     NaN  

[5 rows x 9724 columns]

In [32]:
a = set([i for i in cols if ratings.iloc[1][i] > 3])
len(a)

23

In [33]:
c = set([i for i in cols if ratings.loc[309][i] > 3])
len(c)

88

In [34]:
a-a&c

set()

In [35]:
b = set([i for i in cols if ratings.iloc[494][i] > 3])
len(b)

213

In [36]:
a - a&b

set()

In [37]:
simval.shape

(378,)

In [39]:
r1 = pd.DataFrame([[4,3,5,4],[5,3,0,0],[4,3,3,4],[2,1,0,0],[4,2,0,0],[4,2,0,0]])
r1 = r1/5

In [40]:
u2 = np.array([4,2,0,0])

In [41]:
similarity_calculator(r1, u2)

[0.96083428 0.80218389 0.35434369 0.31002552]
[0.7407749  0.53742985 0.4875026  0.46257015]
[0.16337424 0.30294072 0.49166744 0.46671596]
0.24688662482966256
0.25
0.2232805930641497


array([0.01586006, 0.02583421, 0.01378125, 0.01137424, 0.02039065,
       0.02039065])