In [1]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt

In [2]:
ratings = pd.read_csv("ml-latest-small/ratings.csv")
movies = pd.read_csv("ml-latest-small/movies.csv")

In [3]:
movies.head()

movieId                               title  \
0        1                    Toy Story (1995)   
1        2                      Jumanji (1995)   
2        3             Grumpier Old Men (1995)   
3        4            Waiting to Exhale (1995)   
4        5  Father of the Bride Part II (1995)   

                                        genres  
0  Adventure|Animation|Children|Comedy|Fantasy  
1                   Adventure|Children|Fantasy  
2                               Comedy|Romance  
3                         Comedy|Drama|Romance  
4                                       Comedy

In [4]:
ratings = ratings.drop(["timestamp"],axis=1)
ratings.head()

userId  movieId  rating
0       1        1     4.0
1       1        3     4.0
2       1        6     4.0
3       1       47     5.0
4       1       50     5.0

In [5]:
ratings = ratings.pivot_table(index=["userId"], columns=["movieId"], values="rating")
ratings.head()

movieId  1       2       3       4       5       6       7       8       \
userId                                                                    
1           4.0     NaN     4.0     NaN     NaN     4.0     NaN     NaN   
2           NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
3           NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
4           NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
5           4.0     NaN     NaN     NaN     NaN     NaN     NaN     NaN   

movieId  9       10       ...    193565  193567  193571  193573  193579  \
userId                    ...                                             
1           NaN     NaN   ...       NaN     NaN     NaN     NaN     NaN   
2           NaN     NaN   ...       NaN     NaN     NaN     NaN     NaN   
3           NaN     NaN   ...       NaN     NaN     NaN     NaN     NaN   
4           NaN     NaN   ...       NaN     NaN     NaN     NaN     NaN   
5           NaN     NaN   ...       NaN     NaN     NaN     NaN     NaN   

movieId  193581  193583  193585  193587  193609  
userId                                           
1           NaN     NaN     NaN     NaN     NaN  
2           NaN     NaN     NaN     NaN     NaN  
3           NaN     NaN     NaN     NaN     NaN  
4           NaN     NaN     NaN     NaN     NaN  
5           NaN     NaN     NaN     NaN     NaN  

[5 rows x 9724 columns]

In [186]:
ratedef = ratings.fillna(0)
ratedef = ratedef.div(5)
ratedef.head()

movieId  1       2       3       4       5       6       7       8       \
userId                                                                    
1           0.8     0.0     0.8     0.0     0.0     0.8     0.0     0.0   
2           0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
3           0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
4           0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
5           0.8     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

movieId  9       10       ...    193565  193567  193571  193573  193579  \
userId                    ...                                             
1           0.0     0.0   ...       0.0     0.0     0.0     0.0     0.0   
2           0.0     0.0   ...       0.0     0.0     0.0     0.0     0.0   
3           0.0     0.0   ...       0.0     0.0     0.0     0.0     0.0   
4           0.0     0.0   ...       0.0     0.0     0.0     0.0     0.0   
5           0.0     0.0   ...       0.0     0.0     0.0     0.0     0.0   

movieId  193581  193583  193585  193587  193609  
userId                                           
1           0.0     0.0     0.0     0.0     0.0  
2           0.0     0.0     0.0     0.0     0.0  
3           0.0     0.0     0.0     0.0     0.0  
4           0.0     0.0     0.0     0.0     0.0  
5           0.0     0.0     0.0     0.0     0.0  

[5 rows x 9724 columns]

In [258]:
p = []
p.append([2,3])
p.append([3,10])
p = np.array(p)
q = np.array([3,4])
p
for i in p:
    print(i)

[2 3]
[ 3 10]


In [179]:
current = np.array(ratedef.iloc[2])
user = current
userlen = np.sum(user>0)
intersect = np.sum(current * user > 0)
temp = intersect / (np.sum(current>0) + userlen - intersect)


39

In [116]:
def sigmoid(value):
    return 1/(1 + np.exp(-value))

In [238]:
def proximity(ratings, user):
#     prox = np.array(ratings.shape)
    prox = []
    for index, row in ratings.iterrows():
        current = np.array(row)
#         temp = 1 - sigmoid(np.absolute(current - user))
        temp = 1 - sigmoid(current - user)
        prox.append(temp)
    prox = np.array(prox)
    print(prox[2])
    return prox

In [239]:
def significance(ratings, rmedian, user):
    sign = []
    for index, row in ratings.iterrows():
        current = np.array(row)
#         temp = sigmoid(np.absolute(current - rmedian)*np.absolute(user - rmedian))
        temp = sigmoid((current - rmedian)*(user - rmedian))
        sign.append(temp)
    sign = np.array(sign)
    print(sign[2])
    return sign

In [240]:
def singularity(ratings, mmeans, user):
    sin = []
    for index, row in ratings.iterrows():
        current = np.array(row)
#         temp = 1 - sigmoid(np.absolute((current+user)/2 - mmeans))
        temp = 1 - sigmoid((current+user)/2 - mmeans)
        sin.append(temp)
    sin = np.array(sin)
    print(sin[2])
    return sin

In [264]:
def pss(ratings, user):
    median = np.median(np.array(ratings))
    mmeans = np.array(ratings.mean())
#     simpss = proximity(ratings, user) * significance(ratings, median, user) * singularity(ratings, mmeans, user)
#     simpss = np.cross(np.cross(proximity(ratings, user), significance(ratings, median, user)), singularity(ratings, mmeans, user))
    simpss = []
    prox = proximity(ratings, user)
    sign = significance(ratings, median, user)
    sin = singularity(ratings, mmeans, user)
    print(prox.shape)
    print(sign.shape)
    totalusers = len(prox)
    for i in range(totalusers):
        temp0 = np.cross(prox[i], sign[i])
        temp = np.cross(temp0, sin[i])
        simpss.append(temp)
#     simpss = np.sum(simpss, axis=1)
    print(simpss[2])
    return simpss

In [242]:
def jaccard(ratings, user):
    jac = []
    inte = []
    userlen = np.sum(user>0)
    for index, row in ratings.iterrows():
        current = np.array(row)
        intersect = np.sum(current * user > 0)
#         temp = intersect / (np.sum(current>0) + userlen - intersect)
        temp = intersect / (np.sum(current>0) * userlen)
        jac.append(temp)
        inte.append(intersect)
    jac = np.array(jac)
    print(jac[2])
#     print(user)
#     print(rating)
    return jac

In [243]:
def jpss(ratings, user):
    return pss(ratings, user) * jaccard(ratings, user)

In [248]:
def urp(ratings, user):
    urprate = []
    umean = np.mean(user)
    ustd = np.std(user)
    for index, row in ratings.iterrows():
        current = np.array(row)
#         temp = 1 + sigmoid(np.absolute((umean - np.mean(current))*(ustd - np.std(current))))
        temp = 1 - sigmoid((umean - np.mean(current))*(ustd - np.std(current)))
        urprate.append(temp)
    urprate = np.array(urprate)
    print(urprate[2])
    return urprate

In [249]:
def similarity_calculator(ratings, user):
    return jpss(ratings, user) * urp(ratings, user)

In [260]:
testuser = np.array(ratedef.iloc[0])
testuser

array([0.8, 0. , 0.8, ..., 0. , 0. , 0. ])

In [265]:
simval = similarity_calculator(ratedef, testuser)

[0.68997448 0.5        0.68997448 ... 0.5        0.5        0.5       ]
[0.5 0.5 0.5 ... 0.5 0.5 0.5]
[0.46913765 0.53090318 0.4147347  ... 0.50028689 0.50028689 0.50032787]
(610, 9724)
(610, 9724)


ValueError: incompatible dimensions for cross product
(dimension must be 2 or 3)

In [252]:
simval

array([2.62331346, 0.18183533, 0.47338334, 0.54556516, 0.77875671,
       0.27390095, 0.44921759, 0.84114249, 0.28648838, 0.11254314,
       0.65838205, 0.16475427, 0.51036401, 0.71380796, 0.48648784,
       0.69786241, 0.9514905 , 0.35988578, 0.45187641, 0.35656103,
       0.2752503 , 0.15474985, 0.36914933, 0.59749217, 0.70993239,
       0.87929412, 0.89540546, 0.33106845, 0.64971964, 0.62021946,
       0.89597709, 0.56718502, 0.45406741, 0.45904014, 0.68801952,
       0.43921802, 1.38172832, 0.64139027, 1.34196085, 0.4084122 ,
       0.32585679, 0.46550411, 0.50677668, 0.71384609, 0.65035654,
       0.69025494, 0.24395169, 0.71903667, 0.87919987, 0.21071459,
       0.28953602, 0.16142802, 0.52749699, 0.95895287, 0.63309602,
       0.8020731 , 0.60999685, 0.61012314, 0.93353782, 0.47955579,
       0.81104391, 0.20546271, 0.50107971, 0.55406997, 0.38766844,
       0.49722511, 0.80552473, 0.30555652, 0.85926618, 0.38218255,
       0.75332572, 1.17140806, 0.11212187, 0.19227172, 0.76353

In [ ]:
simval

In [95]:
simval.shape

(610,)

In [185]:
jaccard(ratedef, testuser)

0.0


array([0.02651515, 0.        , 1.        , 0.00393701, 0.01219512,
       0.00857143, 0.        , 0.01176471, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.01162791, 0.01754386,
       0.02238806, 0.02857143, 0.01121495, 0.00678426, 0.01811594,
       0.00626305, 0.01282051, 0.00628931, 0.00675676, 0.015625  ,
       0.        , 0.00578035, 0.015     , 0.01694915, 0.        ,
       0.01136364, 0.01438849, 0.015625  , 0.00806452, 0.        ,
       0.        , 0.        , 0.00862069, 0.01459854, 0.0070922 ,
       0.00392157, 0.01698514, 0.        , 0.01162791, 0.01154734,
       0.        , 0.01129944, 0.        , 0.01694915, 0.01453488,
       0.02051282, 0.        , 0.        , 0.        , 0.01587302,
       0.        , 0.01377953, 0.01342282, 0.02097902, 0.01666667,
       0.01298701, 0.00496278, 0.00649351, 0.01459854, 0.01388889,
       0.01587302, 0.        , 0.01089494, 0.        , 0.03061224,
       0.01369863, 0.02439024, 0.00403226, 0.00934579, 0.00934

In [227]:
r1 = pd.DataFrame([[4,3,5,4],[5,3,0,0],[4,3,3,4],[2,1,0,0],[4,2,0,0],[4,2,0,0]])
r1 = r1/5

In [228]:
u2 = np.array([4,2,0,0])

In [231]:
similarity_calculator(r1, u2)

[0.96083428 0.80218389 0.35434369 0.31002552]
[0.7407749  0.53742985 0.4875026  0.46257015]
[0.16337424 0.30294072 0.49166744 0.46671596]
0.398750026156671
0.25
1.7767194069358503


array([0.15942463, 0.51240298, 0.17711673, 0.48159767, 0.51219734,
       0.51219734])

In [ ]:
0.1778