In [1]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt

In [38]:
ratings = pd.read_csv("ml-latest-small/ratings.csv")
moviesdf = pd.read_csv("ml-laatest-small/movies.csv")

In [39]:
moviesdf.head()

movieId                               title  \
0        1                    Toy Story (1995)   
1        2                      Jumanji (1995)   
2        3             Grumpier Old Men (1995)   
3        4            Waiting to Exhale (1995)   
4        5  Father of the Bride Part II (1995)   

                                        genres  
0  Adventure|Animation|Children|Comedy|Fantasy  
1                   Adventure|Children|Fantasy  
2                               Comedy|Romance  
3                         Comedy|Drama|Romance  
4                                       Comedy

In [40]:
ratings = ratings.drop(["timestamp"],axis=1)
ratings.head()

userId  movieId  rating
0       1        1     4.0
1       1        3     4.0
2       1        6     4.0
3       1       47     5.0
4       1       50     5.0

In [41]:
ratings = ratings.pivot_table(index=["userId"], columns=["movieId"], values="rating")
ratings.head()

movieId  1       2       3       4       5       6       7       8       \
userId                                                                    
1           4.0     NaN     4.0     NaN     NaN     4.0     NaN     NaN   
2           NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
3           NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
4           NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
5           4.0     NaN     NaN     NaN     NaN     NaN     NaN     NaN   

movieId  9       10       ...    193565  193567  193571  193573  193579  \
userId                    ...                                             
1           NaN     NaN   ...       NaN     NaN     NaN     NaN     NaN   
2           NaN     NaN   ...       NaN     NaN     NaN     NaN     NaN   
3           NaN     NaN   ...       NaN     NaN     NaN     NaN     NaN   
4           NaN     NaN   ...       NaN     NaN     NaN     NaN     NaN   
5           NaN     NaN   ...       NaN     NaN     NaN     NaN     NaN   

movieId  193581  193583  193585  193587  193609  
userId                                           
1           NaN     NaN     NaN     NaN     NaN  
2           NaN     NaN     NaN     NaN     NaN  
3           NaN     NaN     NaN     NaN     NaN  
4           NaN     NaN     NaN     NaN     NaN  
5           NaN     NaN     NaN     NaN     NaN  

[5 rows x 9724 columns]

In [6]:
cols = ratings.columns
cols

Int64Index([     1,      2,      3,      4,      5,      6,      7,      8,
                 9,     10,
            ...
            193565, 193567, 193571, 193573, 193579, 193581, 193583, 193585,
            193587, 193609],
           dtype='int64', name='movieId', length=9724)

In [7]:
ratebool = ratings>0
# ratebool.iloc[].sum()
# ratings.index

In [8]:
ratedef = ratings.fillna(0)
ratedef = ratedef.div(5)
ratedef.head()

movieId  1       2       3       4       5       6       7       8       \
userId                                                                    
1           0.8     0.0     0.8     0.0     0.0     0.8     0.0     0.0   
2           0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
3           0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
4           0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
5           0.8     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

movieId  9       10       ...    193565  193567  193571  193573  193579  \
userId                    ...                                             
1           0.0     0.0   ...       0.0     0.0     0.0     0.0     0.0   
2           0.0     0.0   ...       0.0     0.0     0.0     0.0     0.0   
3           0.0     0.0   ...       0.0     0.0     0.0     0.0     0.0   
4           0.0     0.0   ...       0.0     0.0     0.0     0.0     0.0   
5           0.0     0.0   ...       0.0     0.0     0.0     0.0     0.0   

movieId  193581  193583  193585  193587  193609  
userId                                           
1           0.0     0.0     0.0     0.0     0.0  
2           0.0     0.0     0.0     0.0     0.0  
3           0.0     0.0     0.0     0.0     0.0  
4           0.0     0.0     0.0     0.0     0.0  
5           0.0     0.0     0.0     0.0     0.0  

[5 rows x 9724 columns]

In [9]:
p = []
p.append([2,3])
p.append([3,10])
p = np.array(p)
q = np.array([3,4])
p
for i in p:
    print(i)

[2 3]
[ 3 10]


In [10]:
current = np.array(ratedef.iloc[2])
user = current
userlen = np.sum(user>0)
intersect = np.sum(current * user > 0)
temp = intersect / (np.sum(current>0) + userlen - intersect)
# ((ratedef>0)*ratedef).head()

In [11]:
def sigmoid(value):
    return 1/(1 + np.exp(-value))

In [12]:
def proximity(ratings, user):
#     prox = np.array(ratings.shape)
    prox = []
    for index, row in ratings.iterrows():
        current = np.array(row)
#         temp = 1 - sigmoid(np.absolute(current - user))
        temp = 1 - sigmoid(current - user)
        prox.append(temp)
    prox = np.array(prox)
    print(prox[2])
    return prox

In [13]:
def significance(ratings, rmedian, user):
    sign = []
    for index, row in ratings.iterrows():
        current = np.array(row)
#         temp = sigmoid(np.absolute(current - rmedian)*np.absolute(user - rmedian))
        temp = sigmoid((current - rmedian)*(user - rmedian))
        sign.append(temp)
    sign = np.array(sign)
    print(sign[2])
    return sign

In [14]:
def singularity(ratings, mmeans, user):
    sin = []
    for index, row in ratings.iterrows():
        current = np.array(row)
#         temp = 1 - sigmoid(np.absolute((current+user)/2 - mmeans))
        temp = 1 - sigmoid((current+user)/2 - mmeans)
        sin.append(temp)
    sin = np.array(sin)
    print(sin[2])
    return sin

In [15]:
def pss(ratings, user):
    median = np.median(np.array(ratings))
    mmeans = np.array(ratings.mean())
    simpss = proximity(ratings, user) * significance(ratings, median, user) * singularity(ratings, mmeans, user)
    simpss = simpss * (user>0)
#     simpss = np.cross(np.cross(proximity(ratings, user), significance(ratings, median, user)), singularity(ratings, mmeans, user))
#     simpss = []
#     for index, row in ratings.iterrows():
#         current = np.array(row)
        
    simpss = np.sum(simpss, axis=1)
    print(simpss[2])
    return simpss

In [16]:
def jaccard(ratings, user):
    jac = []
    inte = []
    userlen = np.sum(user>0)
    for index, row in ratings.iterrows():
        current = np.array(row)
        intersect = np.sum(current * user > 0)
#         temp = intersect / (np.sum(current>0) + userlen - intersect)
        temp = intersect / (np.sum(current>0) * userlen)
        jac.append(temp)
        inte.append(intersect)
    jac = np.array(jac)
    print(jac[2])
#     print(user)
#     print(rating)
    return jac

In [17]:
def jpss(ratings, user):
    return pss(ratings, user) * jaccard(ratings, user)

In [18]:
def urp(ratings, user):
    urprate = []
    umean = np.mean(user)
    ustd = np.std(user)
    for index, row in ratings.iterrows():
        current = np.array(row)
#         temp = 1 + sigmoid(np.absolute((umean - np.mean(current))*(ustd - np.std(current))))
        temp = 1 - sigmoid((umean - np.mean(current))*(ustd - np.std(current)))
        urprate.append(temp)
    urprate = np.array(urprate)
    print(urprate[2])
    return urprate

In [19]:
def similarity_calculator(ratings, user):
    return jpss(ratings, user) * urp(ratings, user)

In [20]:
type(ratings.index)

pandas.core.indexes.numeric.Int64Index

In [59]:
nk = []
for i in ratedef.index:
#     if ratebool.loc[i].sum() > 50:
    nk.append(ratedef.loc[i])
ratedefactive = pd.DataFrame(nk)
ratedefactive.head()

movieId  1       2       3       4       5       6       7       8       \
1           0.8     0.0     0.8     0.0     0.0     0.8     0.0     0.0   
2           0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
3           0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
4           0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
5           0.8     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

movieId  9       10       ...    193565  193567  193571  193573  193579  \
1           0.0     0.0   ...       0.0     0.0     0.0     0.0     0.0   
2           0.0     0.0   ...       0.0     0.0     0.0     0.0     0.0   
3           0.0     0.0   ...       0.0     0.0     0.0     0.0     0.0   
4           0.0     0.0   ...       0.0     0.0     0.0     0.0     0.0   
5           0.0     0.0   ...       0.0     0.0     0.0     0.0     0.0   

movieId  193581  193583  193585  193587  193609  
1           0.0     0.0     0.0     0.0     0.0  
2           0.0     0.0     0.0     0.0     0.0  
3           0.0     0.0     0.0     0.0     0.0  
4           0.0     0.0     0.0     0.0     0.0  
5           0.0     0.0     0.0     0.0     0.0  

[5 rows x 9724 columns]

In [86]:
ratedefactive.mean()

movieId
1         0.276393
2         0.123770
3         0.055574
4         0.005410
5         0.049344
6         0.131967
7         0.056393
8         0.007541
9         0.016393
10        0.151311
11        0.084262
12        0.015082
13        0.008197
14        0.022623
15        0.012787
16        0.105574
17        0.082951
18        0.024262
19        0.078689
20        0.012295
21        0.101967
22        0.038033
23        0.016393
24        0.028689
25        0.090328
26        0.014918
27        0.009836
28        0.015246
29        0.050000
30        0.002951
            ...   
188189    0.001475
188301    0.003607
188675    0.001148
188751    0.001475
188797    0.001311
188833    0.001475
189043    0.000820
189111    0.000984
189333    0.002459
189381    0.000820
189547    0.000328
189713    0.000820
190183    0.001148
190207    0.000492
190209    0.001311
190213    0.000328
190215    0.000492
190219    0.000328
190221    0.000328
191005    0.001475
193565    0.001148
1935

In [60]:
testuser = np.array(ratedef.iloc[0])
testuser

array([0.8, 0. , 0.8, ..., 0. , 0. , 0. ])

In [61]:
simval = similarity_calculator(ratedefactive, testuser)

[0.68997448 0.5        0.68997448 ... 0.5        0.5        0.5       ]
[0.5 0.5 0.5 ... 0.5 0.5 0.5]
[0.46913765 0.53090318 0.4147347  ... 0.50028689 0.50028689 0.50032787]
33.60762780569397
0.0007736516357206013
0.49955090196234875


In [62]:
simval[:10]

array([0.05332432, 0.00499975, 0.01298862, 0.01451423, 0.02115593,
       0.00736896, 0.01208094, 0.02283129, 0.0078447 , 0.00310666])

In [63]:
topN = sorted([(simval[i],i) for i in range(len(simval))],reverse=True)
topN[:5]

[(0.05332431838804949, 0),
 (0.042242414970638145, 493),
 (0.0394204553547162, 163),
 (0.0375368677863755, 398),
 (0.03753354814505721, 36)]

In [64]:
topNindex = [i[1] for i in topN][:5]
topNindex

[0, 493, 163, 398, 36]

In [65]:
movies = []
topNnumpy = []

for index in topNindex:
    movies.extend([i for i in cols if ratings.iloc[index][i] > 3])
    topNnumpy.append(ratings.iloc[index])
topNdf = pd.DataFrame(topNnumpy)
movies = set(movies)

In [66]:
len(movies)

237

In [67]:
topNdf

movieId  1       2       3       4       5       6       7       8       \
1           4.0     NaN     4.0     NaN     NaN     4.0     NaN     NaN   
494         NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
164         NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
399         4.0     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
37          NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   

movieId  9       10       ...    193565  193567  193571  193573  193579  \
1           NaN     NaN   ...       NaN     NaN     NaN     NaN     NaN   
494         NaN     NaN   ...       NaN     NaN     NaN     NaN     NaN   
164         NaN     NaN   ...       NaN     NaN     NaN     NaN     NaN   
399         NaN     NaN   ...       NaN     NaN     NaN     NaN     NaN   
37          NaN     NaN   ...       NaN     NaN     NaN     NaN     NaN   

movieId  193581  193583  193585  193587  193609  
1           NaN     NaN     NaN     NaN     NaN  
494         NaN     NaN     NaN     NaN     NaN  
164         NaN     NaN     NaN     NaN     NaN  
399         NaN     NaN     NaN     NaN     NaN  
37          NaN     NaN     NaN     NaN     NaN  

[5 rows x 9724 columns]

In [104]:
a = set([i for i in cols if ratings.iloc[1][i] > 0])
len(a)

29

In [105]:
c = set([i for i in cols if ratings.iloc[164][i] > 0])
len(c)

65

In [106]:
b = set([i for i in cols if ratings.iloc[494][i] > 0])
len(b)

265

In [107]:
len(a&c)

0

In [108]:
a&c

set()

In [110]:
len(a&b)

18

In [109]:
a&b

{318,
 333,
 1704,
 3578,
 6874,
 46970,
 48516,
 58559,
 68157,
 74458,
 79132,
 80489,
 80906,
 89774,
 91658,
 99114,
 106782,
 122882}

In [74]:
simval.shape

(610,)

In [96]:
moviesa = [moviesdf.loc[moviesdf['movieId']==i]['title'] for i in a]

In [97]:
moviesa

[8550    Ex Machina (2015)
 Name: title, dtype: object, 8681    Mad Max: Fury Road (2015)
 Name: title, dtype: object, 6315    Departed, The (2006)
 Name: title, dtype: object, 7768    Dark Knight Rises, The (2012)
 Name: title, dtype: object, 7436    Inside Job (2010)
 Name: title, dtype: object, 8828    The Jinx: The Life and Deaths of Robert Durst ...
 Name: title, dtype: object, 7372    Inception (2010)
 Name: title, dtype: object, 8305    Wolf of Wall Street, The (2013)
 Name: title, dtype: object, 1284    Good Will Hunting (1997)
 Name: title, dtype: object, 8466    Whiplash (2014)
 Name: title, dtype: object, 8063    Django Unchained (2012)
 Name: title, dtype: object, 7697    Warrior (2011)
 Name: title, dtype: object, 7010    Inglourious Basterds (2009)
 Name: title, dtype: object, 6710    Dark Knight, The (2008)
 Name: title, dtype: object, 7590    Louis C.K.: Hilarious (2010)
 Name: title, dtype: object, 291    Tommy Boy (1995)
 Name: title, dtype: object, 2674    Gladiator 

In [98]:
moviesb = [moviesdf.loc[moviesdf['movieId']==i]['title'] for i in b]

In [99]:
moviesb

[7043    Hangover, The (2009)
 Name: title, dtype: object, 8681    Mad Max: Fury Road (2015)
 Name: title, dtype: object, 8683    Star Wars: Episode VII - The Force Awakens (2015)
 Name: title, dtype: object, 7436    Inside Job (2010)
 Name: title, dtype: object, 1939    Matrix, The (1999)
 Name: title, dtype: object, 7776    Girl with the Dragon Tattoo, The (2011)
 Name: title, dtype: object, 461    Schindler's List (1993)
 Name: title, dtype: object, 18    Ace Ventura: When Nature Calls (1995)
 Name: title, dtype: object, 8005    Argo (2012)
 Name: title, dtype: object, 8691    Deadpool (2016)
 Name: title, dtype: object, 8099    Side Effects (2013)
 Name: title, dtype: object, 809    William Shakespeare's Romeo + Juliet (1996)
 Name: title, dtype: object, 3414    Planet of the Apes (2001)
 Name: title, dtype: object, 483    Nightmare Before Christmas, The (1993)
 Name: title, dtype: object, 1183    Men in Black (a.k.a. MIB) (1997)
 Name: title, dtype: object, 46    Usual Suspects, T

In [80]:
moviesc = [moviesdf.loc[moviesdf['movieId']==i]['title'] for i in c]

In [81]:
moviesc

[990    Indiana Jones and the Last Crusade (1989)
 Name: title, dtype: object, 793    Die Hard (1988)
 Name: title, dtype: object, 615    Independence Day (a.k.a. ID4) (1996)
 Name: title, dtype: object, 800    Long Kiss Goodnight, The (1996)
 Name: title, dtype: object, 2983    Crouching Tiger, Hidden Dragon (Wo hu cang lon...
 Name: title, dtype: object, 898    Star Wars: Episode V - The Empire Strikes Back...
 Name: title, dtype: object, 1183    Men in Black (a.k.a. MIB) (1997)
 Name: title, dtype: object, 900    Raiders of the Lost Ark (Indiana Jones and the...
 Name: title, dtype: object, 902    Aliens (1986)
 Name: title, dtype: object, 903    Good, the Bad and the Ugly, The (Buono, il bru...
 Name: title, dtype: object, 2713    Man with the Golden Gun, The (1974)
 Name: title, dtype: object, 911    Star Wars: Episode VI - Return of the Jedi (1983)
 Name: title, dtype: object, 1576    Indiana Jones and the Temple of Doom (1984)
 Name: title, dtype: object, 2722    Guns of Navaron

In [100]:
moviesab = [moviesdf.loc[moviesdf['movieId']==i]['title'] for i in a&b]

In [101]:
moviesab

[8681    Mad Max: Fury Road (2015)
 Name: title, dtype: object, 6315    Departed, The (2006)
 Name: title, dtype: object, 4615    Kill Bill: Vol. 1 (2003)
 Name: title, dtype: object, 6253    Talladega Nights: The Ballad of Ricky Bobby (2...
 Name: title, dtype: object, 1284    Good Will Hunting (1997)
 Name: title, dtype: object, 7415    Town, The (2010)
 Name: title, dtype: object, 7436    Inside Job (2010)
 Name: title, dtype: object, 8063    Django Unchained (2012)
 Name: title, dtype: object, 291    Tommy Boy (1995)
 Name: title, dtype: object, 7697    Warrior (2011)
 Name: title, dtype: object, 7258    Shutter Island (2010)
 Name: title, dtype: object, 2674    Gladiator (2000)
 Name: title, dtype: object, 7372    Inception (2010)
 Name: title, dtype: object, 7010    Inglourious Basterds (2009)
 Name: title, dtype: object, 8305    Wolf of Wall Street, The (2013)
 Name: title, dtype: object, 6710    Dark Knight, The (2008)
 Name: title, dtype: object]